// Generated by CoffeeScript 1.4.0
(function() {
  var Gadget, ipad, iphone,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Gadget = (function() {
    var _price;

    Gadget.CITY = "beijing";

    Gadget.create = function(name, price) {
      return new Gadget(name, price);
    };

    _price = 0;

    function Gadget(name, price) {
      this.name = name;
      this.sell = __bind(this.sell, this);

      _price = price;
    }

    Gadget.prototype.sell = function() {
      return "Buy " + this.name + " with " + _price + " in " + Gadget.CITY;
    };

    return Gadget;

  })();

  iphone = new Gadget("iphone", 4999);

  console.log(iphone.name);

  console.log(iphone.sell());

  ipad = Gadget.create("ipad", 3999);

  console.log(ipad.sell());

}).call(this);
